<div class="menu__bottom">
  {% if theme.beian.enable %}
    <a class="menu__bottom--link" href="https://beian.miit.gov.cn"><i class="menu__bottom--icp if i-icp"></i> {{ theme.beian.icp }}</a>
  {% endif %}
  <span>
    <a class="menu__bottom--link" href="{{ theme.url }}"><i class="menu__bottom--theme if i-theme"></i> Zexo</a>
     Powered by 
    <a class="menu__bottom--link" href="http://hexo.io">Hexo</a>
  </span>
</div>